/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Curve25519 */

#ifndef _Included_Curve25519
#define _Included_Curve25519
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Curve25519
 * Method:    _sig_length
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Curve25519__1sig_1length
  (JNIEnv *, jclass);

/*
 * Class:     Curve25519
 * Method:    _pubkey_length
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Curve25519__1pubkey_1length
  (JNIEnv *, jclass);

/*
 * Class:     Curve25519
 * Method:    _seckey_length
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Curve25519__1seckey_1length
  (JNIEnv *, jclass);

/*
 * Class:     Curve25519
 * Method:    _crypto_sign
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Curve25519__1crypto_1sign
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     Curve25519
 * Method:    _crypto_verify
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_Curve25519__1crypto_1verify
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     Curve25519
 * Method:    publickey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Curve25519_publickey
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
